-- CRM demo data for the real Seeding schema.
-- Run in Supabase SQL Editor when only anon key is available locally.
-- Password for crmtest@markee.ai: 123123

INSERT INTO public.app_users (id, email, password, name, role, is_active)
VALUES (
  '11111111-1111-4111-8111-111111111111',
  'crmtest@markee.ai',
  '$2b$12$FPwmvaHADfZSmz8nxUALuuzpEEgp/46oPkfaISeeCqO5fmeKkgZFa',
  'CRM Test Admin',
  'admin',
  true
)
ON CONFLICT (email) DO UPDATE SET
  password = EXCLUDED.password,
  name = EXCLUDED.name,
  role = EXCLUDED.role,
  is_active = EXCLUDED.is_active,
  updated_at = now();

WITH seed_user AS (
  SELECT id FROM public.app_users WHERE email = 'crmtest@markee.ai' LIMIT 1
)
INSERT INTO public.customer_leads (
  id,
  customer_name,
  company_name,
  phone,
  email,
  address,
  city,
  website,
  industry,
  tax_code,
  leaded_by,
  is_assigned,
  sdr_id,
  conv_id,
  source_platform,
  status,
  activity_status,
  deal_stage,
  prev_stage,
  follow_up_date,
  decision_maker,
  estimated_budget,
  stage_entered_at,
  customer_since,
  service_package,
  lifetime_value,
  contract_signed_at,
  contract_status,
  warranty_expires_at,
  care_note,
  last_care_at,
  payment_due_date,
  payment_status,
  tags,
  has_budget,
  note,
  reject_reason,
  reject_reason_type,
  review_result,
  last_attachment_url,
  last_attachment_name,
  closed_reason
)
SELECT *
FROM (
  VALUES
  (
    '22222222-2222-4222-8222-222222222201'::uuid,
    'Nguyen Minh An',
    'An Phat Retail',
    '0901000001',
    'an.nguyen@example.com',
    '12 Nguyen Trai',
    'Ho Chi Minh',
    'https://anphat.example.com',
    'Retail',
    '0310000001',
    (SELECT id FROM seed_user),
    true,
    (SELECT id FROM seed_user),
    'crm-seed-new-lead',
    'FB_Inbox',
    'pending',
    'active',
    'new_lead',
    NULL,
    NULL::timestamptz,
    NULL,
    12000000,
    now() - interval '1 day',
    NULL::timestamptz,
    'Goi khoi dong CRM',
    0,
    NULL::timestamptz,
    'active',
    NULL::timestamptz,
    'Khach moi tu inbox, can goi xac nhan nhu cau.',
    NULL::timestamptz,
    now() + interval '14 days',
    'unpaid',
    ARRAY['khach-moi','facebook']::text[],
    true,
    'Khach moi can tu van goi khoi dong.',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    '22222222-2222-4222-8222-222222222202'::uuid,
    'Tran Bao Linh',
    'Linh Foods',
    '0901000002',
    'linh.tran@example.com',
    '45 Le Loi',
    'Ha Noi',
    'https://linhfoods.example.com',
    'F&B',
    '0100000002',
    (SELECT id FROM seed_user),
    true,
    (SELECT id FROM seed_user),
    'crm-seed-overdue',
    'Manual',
    'pending',
    'active',
    'contract_sent',
    NULL,
    NULL::timestamptz,
    'Tran Bao Linh',
    45000000,
    now() - interval '9 days',
    NULL::timestamptz,
    'Goi seeding nang cao',
    45000000,
    NULL::timestamptz,
    'active',
    NULL::timestamptz,
    'Da gui hop dong, dang tre han thanh toan.',
    now() - interval '3 days',
    now() - interval '5 days',
    'unpaid',
    ARRAY['tre-han','hop-dong']::text[],
    true,
    'Can nhac thanh toan va chot ngay giao hang.',
    NULL,
    NULL,
    NULL,
    'https://example.com/contracts/linh-foods.pdf',
    'hop-dong-linh-foods.pdf',
    NULL
  ),
  (
    '22222222-2222-4222-8222-222222222203'::uuid,
    'Le Quoc Hung',
    'Hung Logistics',
    '0901000003',
    'hung.le@example.com',
    '8 Pham Van Dong',
    'Da Nang',
    'https://hunglogistics.example.com',
    'Logistics',
    '0400000003',
    (SELECT id FROM seed_user),
    true,
    (SELECT id FROM seed_user),
    'crm-seed-won',
    'Zalo',
    'closed',
    'active',
    'won',
    NULL,
    NULL::timestamptz,
    'Le Quoc Hung',
    58000000,
    now() - interval '20 days',
    now() - interval '18 days',
    'Goi CRM + CSKH',
    58000000,
    now() - interval '18 days',
    'active',
    now() + interval '347 days',
    'Da thanh toan du, can follow up onboarding.',
    now() - interval '2 days',
    now() - interval '16 days',
    'paid',
    ARRAY['deal-thang','zalo']::text[],
    true,
    'Deal da thang, da ky hop dong.',
    NULL,
    NULL,
    'Qualify',
    'https://example.com/contracts/hung-logistics.pdf',
    'hop-dong-hung-logistics.pdf',
    'Khach dong y goi CRM + CSKH 12 thang.'
  ),
  (
    '22222222-2222-4222-8222-222222222204'::uuid,
    'Pham Thu Ha',
    'Ha Beauty',
    '0901000004',
    'ha.pham@example.com',
    '19 Ba Trieu',
    'Can Tho',
    'https://habeauty.example.com',
    'Beauty',
    '1800000004',
    (SELECT id FROM seed_user),
    true,
    (SELECT id FROM seed_user),
    'crm-seed-lost',
    'FB_Group',
    'rejected',
    'churned',
    'lost',
    NULL,
    NULL::timestamptz,
    'Pham Thu Ha',
    18000000,
    now() - interval '12 days',
    NULL::timestamptz,
    'Goi lead generation',
    0,
    NULL::timestamptz,
    'active',
    NULL::timestamptz,
    'Khach chon nha cung cap khac.',
    now() - interval '8 days',
    NULL::timestamptz,
    'unpaid',
    ARRAY['deal-mat','fb-group']::text[],
    true,
    'Khach tu choi sau bao gia.',
    'Gia chua phu hop va da chon ben khac.',
    'Khong_du_tai_chinh',
    'Disqualify',
    'https://example.com/proposals/ha-beauty.pdf',
    'bao-gia-ha-beauty.pdf',
    NULL
  ),
  (
    '22222222-2222-4222-8222-222222222205'::uuid,
    'Do Nam Khanh',
    'Khanh Education',
    '0901000005',
    'khanh.do@example.com',
    '77 Dien Bien Phu',
    'Ho Chi Minh',
    'https://khanhedu.example.com',
    'Education',
    '0310000005',
    (SELECT id FROM seed_user),
    true,
    (SELECT id FROM seed_user),
    'crm-seed-on-hold',
    'Manual',
    'pending',
    'paused',
    'on_hold',
    'negotiation',
    now() + interval '7 days',
    'Do Nam Khanh',
    32000000,
    now() - interval '6 days',
    NULL::timestamptz,
    'Goi automation tuyen sinh',
    32000000,
    NULL::timestamptz,
    'maintenance',
    NULL::timestamptz,
    'Tam giu den khi khach duyet ngan sach quy moi.',
    now() - interval '1 day',
    now() + interval '21 days',
    'partial',
    ARRAY['tam-giu','education']::text[],
    true,
    'Tam dung theo yeu cau khach, hen follow up sau 7 ngay.',
    NULL,
    NULL,
    NULL,
    'https://example.com/proposals/khanh-education.pdf',
    'de-xuat-khanh-education.pdf',
    NULL
  )
) AS data(
  id,
  customer_name,
  company_name,
  phone,
  email,
  address,
  city,
  website,
  industry,
  tax_code,
  leaded_by,
  is_assigned,
  sdr_id,
  conv_id,
  source_platform,
  status,
  activity_status,
  deal_stage,
  prev_stage,
  follow_up_date,
  decision_maker,
  estimated_budget,
  stage_entered_at,
  customer_since,
  service_package,
  lifetime_value,
  contract_signed_at,
  contract_status,
  warranty_expires_at,
  care_note,
  last_care_at,
  payment_due_date,
  payment_status,
  tags,
  has_budget,
  note,
  reject_reason,
  reject_reason_type,
  review_result,
  last_attachment_url,
  last_attachment_name,
  closed_reason
)
ON CONFLICT (id) DO UPDATE SET
  customer_name = EXCLUDED.customer_name,
  company_name = EXCLUDED.company_name,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  address = EXCLUDED.address,
  city = EXCLUDED.city,
  website = EXCLUDED.website,
  industry = EXCLUDED.industry,
  tax_code = EXCLUDED.tax_code,
  leaded_by = EXCLUDED.leaded_by,
  is_assigned = EXCLUDED.is_assigned,
  sdr_id = EXCLUDED.sdr_id,
  conv_id = EXCLUDED.conv_id,
  source_platform = EXCLUDED.source_platform,
  status = EXCLUDED.status,
  activity_status = EXCLUDED.activity_status,
  deal_stage = EXCLUDED.deal_stage,
  prev_stage = EXCLUDED.prev_stage,
  follow_up_date = EXCLUDED.follow_up_date,
  decision_maker = EXCLUDED.decision_maker,
  estimated_budget = EXCLUDED.estimated_budget,
  stage_entered_at = EXCLUDED.stage_entered_at,
  customer_since = EXCLUDED.customer_since,
  service_package = EXCLUDED.service_package,
  lifetime_value = EXCLUDED.lifetime_value,
  contract_signed_at = EXCLUDED.contract_signed_at,
  contract_status = EXCLUDED.contract_status,
  warranty_expires_at = EXCLUDED.warranty_expires_at,
  care_note = EXCLUDED.care_note,
  last_care_at = EXCLUDED.last_care_at,
  payment_due_date = EXCLUDED.payment_due_date,
  payment_status = EXCLUDED.payment_status,
  tags = EXCLUDED.tags,
  has_budget = EXCLUDED.has_budget,
  note = EXCLUDED.note,
  reject_reason = EXCLUDED.reject_reason,
  reject_reason_type = EXCLUDED.reject_reason_type,
  review_result = EXCLUDED.review_result,
  last_attachment_url = EXCLUDED.last_attachment_url,
  last_attachment_name = EXCLUDED.last_attachment_name,
  closed_reason = EXCLUDED.closed_reason,
  updated_at = now();

DELETE FROM public.customer_lead_activity_log
WHERE customer_id IN (
  '22222222-2222-4222-8222-222222222201',
  '22222222-2222-4222-8222-222222222202',
  '22222222-2222-4222-8222-222222222203',
  '22222222-2222-4222-8222-222222222204',
  '22222222-2222-4222-8222-222222222205'
);

INSERT INTO public.customer_lead_activity_log (
  customer_id,
  action,
  from_stage,
  to_stage,
  actor_id,
  actor_name,
  note,
  attachment_url,
  attachment_name,
  created_at
)
SELECT
  lead.id,
  'created',
  NULL,
  lead.deal_stage,
  user_row.id,
  user_row.name,
  lead.note,
  lead.last_attachment_url,
  lead.last_attachment_name,
  lead.created_at
FROM public.customer_leads lead
CROSS JOIN public.app_users user_row
WHERE user_row.email = 'crmtest@markee.ai'
  AND lead.conv_id IN (
    'crm-seed-new-lead',
    'crm-seed-overdue',
    'crm-seed-won',
    'crm-seed-lost',
    'crm-seed-on-hold'
  );
