import {
  LayoutDashboard,
  Users,
  CircleUserRound,
  UserCog,
  Folder,
  Tag,
  FileText,
  Radar,
  Send,
  Headset,
  Inbox,
  Globe,
  MessageCircle,
  UsersRound,
  Database,
  Activity,
  Settings,
  ShieldCheck,
  ClipboardList,
  Cable,
  Receipt,
  LayoutTemplate,
  Megaphone,
  Building2,
  FileSearch,
  History,
  FileSignature,
  Funnel,
  UserRoundPlus,
  Target,
  SlidersHorizontal,
  LayoutList,
  TrendingUp,
  MessageSquare,
  MessagesSquare,
  ArrowRight,
  Share2,
  FolderArchive,
  ChartNoAxesCombined,
  Gauge,
  ChartColumn,
  Library,
  Settings2,
  Shield,
  Landmark,
  Package,
  Files,
  GitBranch,
  ListTree,
  ListFilter,
  Plug,
  type LucideIcon,
} from "lucide-react";
import type { MaterialSymbolName } from "@/components/ui";

// Chuyen doi ten icon Material Symbols (dung trong buildEntries() cua
// AllPlatformSidebar.tsx) sang icon lucide-react tuong ung, de tai su dung
// dung 1 nguon cau hinh menu (buildEntries) cho ca 2 kieu hien thi sidebar
// (ban Material cu + ban shadcn moi lay mau tu app.markeeai.com).
const MAP: Partial<Record<MaterialSymbolName, LucideIcon>> = {
  dashboard: LayoutDashboard,
  groups: Users,
  account_circle: CircleUserRound,
  manage_accounts: UserCog,
  folder: Folder,
  category: Tag,
  article: FileText,
  radar: Radar,
  send: Send,
  support_agent: Headset,
  inbox: Inbox,
  travel_explore: Globe,
  chat: MessageCircle,
  group: UsersRound,
  database: Database,
  monitoring: Activity,
  settings: Settings,
  verified_user: ShieldCheck,
  assignment: ClipboardList,
  settings_input_component: Cable,
  request_quote: Receipt,
  star: LayoutTemplate,
  campaign: Megaphone,
  domain: Building2,
  person_search: FileSearch,
  description: FileSignature,
  history: History,
  filter_alt: Funnel,
  person_add: UserRoundPlus,
  // Bổ sung các icon đặc trưng tránh trùng lặp:
  track_changes: Target,
  tune: SlidersHorizontal,
  list_alt: LayoutList,
  trending_up: TrendingUp,
  chat_bubble: MessageSquare,
  arrow_forward: ArrowRight,
  share: Share2,
  folder_shared: FolderArchive,
  // Sidebar CRM redesign (6 nhom phang) — icon nhom + icon muc moi.
  analytics: ChartNoAxesCombined,
  forum: MessagesSquare,
  speed: Gauge,
  bar_chart: ChartColumn,
  local_library: Library,
  settings_applications: Settings2,
  shield: Shield,
  account_balance: Landmark,
  inventory_2: Package,
  folder_copy: Files,
  account_tree: GitBranch,
  schema: ListTree,
  filter_list: ListFilter,
  power: Plug,
};

export function materialToLucideIcon(name: MaterialSymbolName): LucideIcon {
  return MAP[name] ?? FileText;
}
