import { ChannelAccount, ConversationItem } from "./types";

export const MOCK_CHANNEL_ACCOUNTS: ChannelAccount[] = [
  { id: "acc-zalo-1", name: "Zalo Sales 01", channel: "zalo", status: "online", count: 12 },
  { id: "acc-fb-1", name: "Facebook Page A", channel: "facebook", status: "online", count: 18 },
  { id: "acc-tele-1", name: "Telegram Sales", channel: "telegram", status: "offline", count: 0 },
  { id: "acc-wa-1", name: "WhatsApp Business", channel: "whatsapp", status: "online", count: 6 },
  { id: "acc-vb-1", name: "Viber Support", channel: "viber", status: "offline", count: 0 },
  { id: "acc-li-1", name: "LinkedIn Personal", channel: "linkedin", status: "online", count: 2 },
];

export const MOCK_CONVERSATIONS: ConversationItem[] = [
  {
    id: "conv-zalo-hoang",
    channel: "zalo",
    accountId: "acc-zalo-1",
    accountLabel: "Zalo · Sales 01",
    customerName: "Anh Hoàng",
    customerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    unreadCount: 1,
    lastMessageText: "Ok em, để anh xem rồi phản hồi lại nhé. Có thể triển khai trong bao lâu?",
    lastMessageTime: "10:16",
    tags: ["Hot lead", "Chờ báo giá"],
    isCrmMatched: true,
    crmData: {
      matched: true,
      name: "ABC FOOD",
      statusLabel: "Khách hàng tiềm năng",
      phone: "0912 345 678",
      email: "example@abcfood.vn",
      address: "Quận 1, TP. HCM",
      ownerName: "Nguyễn Thị Mai",
      ownerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    },
    opportunity: {
      id: "opp-089",
      code: "OPP-2026-089",
      name: "Dự án triển khai CRM - ABC FOOD",
      amount: "50.000.000đ",
      stage: "Báo giá",
      winRate: "60%",
      ownerName: "Nguyễn Thị Mai",
      updatedAt: "02/10/2026",
    },
    quote: {
      id: "qua-146",
      code: "QUA-2026-146",
      amount: "50.000.000đ",
      status: "Draft",
      ownerName: "Nguyễn Thị Mai",
      createdAt: "02/10/2026",
    },
    messages: [
      {
        id: "msg-z0",
        sender: "system",
        text: "10:00 — Khách hàng kết nối qua Zalo QR Code (Mã giới thiệu: WEBSITE_PAGEMAIN)",
        time: "10:00",
      },
      {
        id: "msg-z1",
        sender: "them",
        senderName: "Anh Hoàng",
        text: "Chào em, bên mình có gói giải pháp CRM nào phù hợp cho doanh nghiệp chế biến thực phẩm tầm 30 nhân sự không?",
        time: "10:05",
      },
      {
        id: "msg-z2",
        sender: "me",
        senderName: "Tôi",
        text: "Dạ em chào anh Hoàng! Cảm ơn anh đã quan tâm. Bên em có gói Pro thiết kế riêng cho ngành sản xuất & bán lẻ thực phẩm rất tối ưu ạ.",
        time: "10:07",
        status: "read",
      },
      {
        id: "msg-z3",
        sender: "them",
        senderName: "Anh Hoàng",
        text: "Gói đó có hỗ trợ đồng bộ đơn hàng với Zalo OA và Messenger không em?",
        time: "10:09",
      },
      {
        id: "msg-z4",
        sender: "me",
        senderName: "Tôi",
        text: "Dạ có đầy đủ ạ! Tất cả tin nhắn Zalo, FB Fanpage, Telegram và lịch sử mua hàng đều được quản lý tập trung trên 1 màn hình duy nhất.",
        time: "10:10",
        status: "read",
      },
      {
        id: "msg-z5",
        sender: "me",
        senderName: "Tôi",
        text: "Em gửi anh sơ đồ tổng quan giao diện quản lý đa kênh bên em nhé:",
        time: "10:11",
        status: "read",
        attachment: {
          type: "image",
          name: "Dashboard-Omnichannel-Markee.jpg",
          size: "1.2 MB",
          url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "msg-z6",
        sender: "me",
        senderName: "Tôi",
        text: "Em đã lập phương án báo giá sơ bộ cho bên mình đây ạ:",
        time: "10:13",
        status: "read",
        attachment: {
          type: "pdf",
          name: "Bao-gia-Markee-Pro-ABCFood.pdf",
          size: "2.4 MB",
        },
      },
      {
        id: "msg-z7",
        sender: "me",
        senderName: "Tôi",
        text: "📑 Báo giá đính kèm: QUA-2026-146 · Gói phần mềm Enterprise CRM · 50.000.000đ (Chiết khấu 10% đăng ký trong tháng 10)",
        time: "10:14",
        status: "read",
      },
      {
        id: "msg-z8",
        sender: "me",
        senderName: "Tôi",
        text: "Anh Hoàng xem qua giúp em bản báo giá nhé. Nếu cần điều chỉnh hạng mục nào anh cứ nhắn em ạ.",
        time: "10:15",
        status: "read",
      },
      {
        id: "msg-z9",
        sender: "them",
        senderName: "Anh Hoàng",
        text: "Ok em, để anh xem rồi phản hồi lại nhé. Có thể triển khai trong bao lâu?",
        time: "10:16",
      },
    ],
    aiSuggestedReply:
      "Dạ gói Pro có thể triển khai trong 3 - 5 ngày tùy vào yêu cầu đặc thù của doanh nghiệp. Em có thể sắp xếp demo chi tiết vào chiều mai cho anh được không ạ?",
  },

  {
    id: "conv-fb-anh",
    channel: "facebook",
    accountId: "acc-fb-1",
    accountLabel: "Facebook Page A",
    customerName: "Lê Thị Ánh",
    customerAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    unreadCount: 0,
    lastMessageText: "Dự án triển khai tháng 10 này bên em còn nhận slot không?",
    lastMessageTime: "10:02",
    tags: ["Đã liên hệ"],
    isCrmMatched: true,
    crmData: {
      matched: true,
      name: "Công ty TNHH Ánh Dương",
      statusLabel: "Khách hàng mới",
      phone: "0988 777 666",
      email: "anh.le@anhduong.vn",
      address: "Cầu Giấy, Hà Nội",
      ownerName: "Lê Văn Nam",
      ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    opportunity: {
      id: "opp-112",
      code: "OPP-2026-112",
      name: "Tích hợp Omnichannel Fanpage",
      amount: "120.000.000đ",
      stage: "Khảo sát",
      winRate: "40%",
      ownerName: "Lê Văn Nam",
      updatedAt: "01/10/2026",
    },
    messages: [
      {
        id: "msg-f0",
        sender: "system",
        text: "09:50 — Nhận tin nhắn từ Facebook Messenger Fanpage Markee AI",
        time: "09:50",
      },
      {
        id: "msg-f1",
        sender: "them",
        senderName: "Lê Thị Ánh",
        text: "Dạ bên mình có hỗ trợ tích hợp Fanpage với CRM không ạ?",
        time: "09:55",
      },
      {
        id: "msg-f2",
        sender: "me",
        senderName: "Tôi",
        text: "Dạ chào chị Ánh! Hệ thống bên em tích hợp tự động Fanpage, Zalo và Telegram vào CRM ạ.",
        time: "09:58",
        status: "read",
      },
      {
        id: "msg-f3",
        sender: "them",
        senderName: "Lê Thị Ánh",
        text: "Dự án triển khai tháng 10 này bên em còn nhận slot không?",
        time: "10:02",
      },
    ],
    aiSuggestedReply:
      "Dạ bên em vẫn còn slot triển khai cho tháng 10 ạ! Chị Ánh cho em xin thời gian thuận tiện để team kĩ thuật qua tư vấn trực tiếp cho chị nhé.",
  },

  {
    id: "conv-tele-tech",
    channel: "telegram",
    accountId: "acc-tele-1",
    accountLabel: "Telegram Sales",
    customerName: "Tech Group",
    customerAvatar: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80",
    unreadCount: 3,
    lastMessageText: "Đã nhận được tài liệu, cảm ơn team!",
    lastMessageTime: "09:48",
    tags: ["Nhóm tư vấn"],
    isCrmMatched: false,
    crmData: {
      matched: false,
    },
    messages: [
      {
        id: "msg-t0",
        sender: "system",
        text: "09:25 — Đã kết nối nhóm Telegram @tech_group_consulting",
        time: "09:25",
      },
      {
        id: "msg-t1",
        sender: "them",
        senderName: "Tech Group Admin",
        text: "Team hỗ trợ gửi giúp tài liệu API v2 với nhé.",
        time: "09:30",
      },
      {
        id: "msg-t2",
        sender: "me",
        senderName: "Tôi",
        text: "Dạ em đã gửi file spec API v2 qua nhóm rồi ạ.",
        time: "09:40",
        status: "read",
      },
      {
        id: "msg-t3",
        sender: "them",
        senderName: "Tech Group Admin",
        text: "Đã nhận được tài liệu, cảm ơn team!",
        time: "09:48",
      },
    ],
    aiSuggestedReply:
      "Dạ không có gì ạ! Nếu trong quá trình tích hợp API v2 gặp vướng mắc gì team cứ nhắn lên group để bên em hỗ trợ kịp thời nhé.",
  },

  {
    id: "conv-li-minh",
    channel: "linkedin",
    accountId: "acc-li-1",
    accountLabel: "LinkedIn Personal",
    customerName: "Nguyễn Văn Minh",
    customerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    unreadCount: 1,
    lastMessageText: "Looking forward to working with your team on the upcoming project.",
    lastMessageTime: "09:30",
    tags: ["Tiềm năng"],
    isCrmMatched: true,
    crmData: {
      matched: true,
      name: "Minh Nguyen Tech Corp",
      statusLabel: "Khách hàng tiềm năng",
      phone: "0903 111 222",
      email: "minh.nguyen@techcorp.com",
      address: "Quận 3, TP. HCM",
      ownerName: "Trần Thị Bình",
      ownerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    },
    messages: [
      {
        id: "msg-l0",
        sender: "system",
        text: "09:10 — Khách hàng nhắn qua LinkedIn InMail Direct Message",
        time: "09:10",
      },
      {
        id: "msg-l1",
        sender: "them",
        senderName: "Nguyễn Văn Minh",
        text: "Hi team, I saw your marketing automation package on LinkedIn.",
        time: "09:15",
      },
      {
        id: "msg-l2",
        sender: "me",
        senderName: "Tôi",
        text: "Hi Mr. Minh! Thank you for reaching out. I'd be happy to share our solutions with you.",
        time: "09:25",
        status: "read",
      },
      {
        id: "msg-l3",
        sender: "them",
        senderName: "Nguyễn Văn Minh",
        text: "Looking forward to working with your team on the upcoming project.",
        time: "09:30",
      },
    ],
    aiSuggestedReply:
      "Thank you Mr. Minh! Would you be available for a brief 15-minute call tomorrow at 10 AM to discuss your project scope?",
  },

  {
    id: "conv-zalo-abc",
    channel: "zalo",
    accountId: "acc-zalo-1",
    accountLabel: "Zalo · Sales 01",
    customerName: "Công ty ABC",
    customerAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
    unreadCount: 0,
    lastMessageText: "Cho tôi xin thêm thông tin dịch vụ chăm sóc khách hàng tự động.",
    lastMessageTime: "09:12",
    tags: ["Quan tâm"],
    isCrmMatched: true,
    crmData: {
      matched: true,
      name: "Công ty Cổ phần ABC",
      statusLabel: "Khách hàng doanh nghiệp",
      phone: "0918 222 333",
      email: "contact@abc.vn",
      address: "Bình Thạnh, TP. HCM",
      ownerName: "Nguyễn Thị Mai",
    },
    messages: [
      {
        id: "msg-zabc1",
        sender: "them",
        senderName: "Công ty ABC",
        text: "Cho tôi xin thêm thông tin dịch vụ chăm sóc khách hàng tự động.",
        time: "09:12",
      },
    ],
  },

  {
    id: "conv-fb-hang",
    channel: "facebook",
    accountId: "acc-fb-1",
    accountLabel: "Facebook Page A",
    customerName: "Phạm Thu Hằng",
    customerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    unreadCount: 0,
    lastMessageText: "Khi nào có thể demo hệ thống ạ?",
    lastMessageTime: "08:55",
    tags: ["Quan tâm"],
    isCrmMatched: true,
    crmData: {
      matched: true,
      name: "Thu Hằng Education",
      statusLabel: "Khách hàng cá nhân",
      phone: "0977 123 456",
      email: "hang.pham@edu.vn",
      address: "Đống Đa, Hà Nội",
      ownerName: "Lê Văn Nam",
    },
    messages: [
      {
        id: "msg-fh1",
        sender: "them",
        senderName: "Phạm Thu Hằng",
        text: "Khi nào có thể demo hệ thống ạ?",
        time: "08:55",
      },
    ],
  },

  {
    id: "conv-tele-support",
    channel: "telegram",
    accountId: "acc-tele-1",
    accountLabel: "Telegram Sales",
    customerName: "IT Support",
    customerAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    unreadCount: 0,
    lastMessageText: "📎 File đính kèm tài liệu hướng dẫn",
    lastMessageTime: "08:20",
    tags: ["Hỗ trợ kĩ thuật"],
    isCrmMatched: false,
    crmData: {
      matched: false,
    },
    messages: [
      {
        id: "msg-ts1",
        sender: "them",
        senderName: "IT Support",
        text: "📎 File đính kèm tài liệu hướng dẫn",
        time: "08:20",
      },
    ],
  },
];
